FROM pytorch/pytorch:latest

RUN apt update && pip install datasets evaluate transformers huggingface_hub accelerate scikit-learn plotly  python-dotenv sentence-transformers streamlit langchain openai rdflib bitsandbytes chromadb langchain-community